### PR TITLE
Enhance LNT ECMP Test cases

### PR DESCRIPTION
**Pull request by sjwahub**
Enhance the script to be more stable.

1.  Test log [ptf_tests_run_nonfrr_2.log](https://github.com/ipdk-io/ovs/files/9975389/ptf_tests_run_nonfrr_2.log)

2.  p4ovs rebuild log as below

```
libtool: finish: PATH="/root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin:/root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/sbin:/root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin:/root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c utilities/ovs-appctl utilities/ovs-testcontroller utilities/ovs-dpctl utilities/ovs-ofctl utilities/ovs-vsctl utilities/gnmi-cli utilities/ovs_pipeline_builder ovsdb/ovsdb-tool ovsdb/ovsdb-client vtep/vtep-ctl '/root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin'
libtool: install: /usr/bin/install -c utilities/ovs-appctl /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin/ovs-appctl
libtool: install: /usr/bin/install -c utilities/ovs-testcontroller /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin/ovs-testcontroller
libtool: install: /usr/bin/install -c utilities/ovs-dpctl /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin/ovs-dpctl
libtool: install: /usr/bin/install -c utilities/ovs-ofctl /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin/ovs-ofctl
libtool: install: /usr/bin/install -c utilities/ovs-vsctl /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin/ovs-vsctl
libtool: install: /usr/bin/install -c utilities/gnmi-cli /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin/gnmi-cli
libtool: install: /usr/bin/install -c utilities/ovs_pipeline_builder /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin/ovs_pipeline_builder
libtool: install: /usr/bin/install -c ovsdb/ovsdb-tool /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin/ovsdb-tool
libtool: install: /usr/bin/install -c ovsdb/ovsdb-client /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin/ovsdb-client
libtool: install: /usr/bin/install -c vtep/vtep-ctl /root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/bin/vtep-ctl
make[3]: Leaving directory '/root/sjwang_ptf/build_emcp_p4ovs'
make[2]: Leaving directory '/root/sjwang_ptf/build_emcp_p4ovs'
make[1]: Leaving directory '/root/sjwang_ptf/build_emcp_p4ovs'
root@wp34:~/sjwang_ptf/build_emcp_p4ovs#
root@wp34:~/sjwang_ptf/build_emcp_p4ovs#


root@wp34:~/sjwang_ptf/build_emcp_p4ovs# ps -ef | grep ovs
root     57078     1  0 09:33 ?        00:00:00 ovsdb-server --remote=punix:/root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options --pidfile --detach
root     57081     1 92 09:33 ?        00:00:11 ovs-vswitchd --pidfile --detach --no-chdir unix:/root/sjwang_ptf/build_emcp_p4ovs/deps/P4OVS_DEPS_INSTALL/var/run/openvswitch/db.sock --mlockall --log-file=/tmp/ovs-vswitchd.log
root     57114 13043  0 09:33 pts/0    00:00:00 grep --color=auto ovs


```

### CODE REVIEW

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-88-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/fe85969058219f20c50ae10c0149486124f94f56

**Comment by sjwahub** [comment]
Enhance the script to be more stable. Test log [ptf_tests_run_lnt_ecmp_2.log](https://github.com/ipdk-io/ovs/files/9967034/ptf_tests_run_lnt_ecmp_2.log)

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-88-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/fe85969058219f20c50ae10c0149486124f94f56

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-88-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/be0bce69ccbc4073f112cac8931e810d00c673ba

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-88-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/2da5722273cfe063bc7c6a6384c09249506211fd

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-88-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/1fa723a03c6a022b219841f9e500a8efdb45b58d

**Review by dkaranjai — APPROVED** [review]
LGTM

**Review by stadju — APPROVED** [review]

**Pull request merged**
