### PR TITLE
Fix Makefile.am to add .github/CODEOWNERS

### PR DESCRIPTION
**Pull request by 5abeel**
Signed-off-by: Sabeel Ansari <sabeel.ansari@intel.com>

### CODE REVIEW

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-43-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/e701317801bf15e0956ee03e52c75d99db380d70

**Review by kkongusa — COMMENTED** [review]
looks good

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-43-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/e701317801bf15e0956ee03e52c75d99db380d70

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-43-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/cfe0bd1fb79bc4657b200dd551c8f2e2dfa4483e

**Review by namratalimaye — APPROVED** [review]
Looks good

**Review by np2-git — APPROVED** [review]
Looks fine

**Pull request merged**
