### PR TITLE
“Make_Required_changes”

### PR DESCRIPTION
**Pull request by hirentha**
Signed-off-by: dpathrabe <deepak.p.pathrabe@intel.com>

### CODE REVIEW

**Comment by hirentha** [comment]
Attached script run logs.
[ptf_link_port_tests.log](https://github.com/ipdk-io/ovs/files/9643467/ptf_link_port_tests.log)

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/db939a4d4c0823a456e335edd0a8b9cf6f5b0ab9

**Review by dkaranjai — APPROVED** [review]
looks good to me.

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/db939a4d4c0823a456e335edd0a8b9cf6f5b0ab9

**Review by sijubaker — APPROVED** [review]
approved !

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/f7b43511a1664adc95d7c3954de132e4b2b189ef

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/5841a05398206e03cb194eb00666703ae62965ba

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/5841a05398206e03cb194eb00666703ae62965ba

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/5841a05398206e03cb194eb00666703ae62965ba

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/b94a99b81c7c02fbbbeb3246316ab12f5b643459

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/b94a99b81c7c02fbbbeb3246316ab12f5b643459

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/b94a99b81c7c02fbbbeb3246316ab12f5b643459

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/52c430b2520a1f2adea4466c726c893ccaabaa8d

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-11/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/52c430b2520a1f2adea4466c726c893ccaabaa8d

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-12/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/33f2235073f6dffcb7d50c1ebb28e8714a4d5708

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-13/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/33f2235073f6dffcb7d50c1ebb28e8714a4d5708

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-73-14/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/33f2235073f6dffcb7d50c1ebb28e8714a4d5708

**Pull request merged**
