### PR TITLE
Modified P4-OVS contributing based on GitHub PR flow

### PR DESCRIPTION
**Pull request by mgaravin**

### CODE REVIEW

**Review by mestery — COMMENTED** [review]
We need to re-enable DCO, so please force push with a `Signed-off-by`.

**Comment by mgaravin** [comment]
> We need to re-enable DCO, so please force push with a `Signed-off-by`.

Fixed!

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/nex-epgsw-ipdkci/GitHub_MultiBranch_Pipelines/ovs/PR-32-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9d9d939c3a45c3f1fd6131316466a2a093c00360

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/nex-epgsw-ipdkci/GitHub_MultiBranch_Pipelines/ovs/PR-32-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/c0a0c5e7f4de98a17c9011b83d44463776fe8a66

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-32-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/80c05354017b2083c5a53e1982eb4e3f80f11773

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-32-11/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/40d78c2a3f2333a9f764441ca9e822b9be9d91c1

**Review by namratalimaye — APPROVED** [review]
Looks good

**Pull request merged**
