### PR TITLE
Move ovs-p4rt.h header file

### PR DESCRIPTION
**Pull request by ffoulkes**
- Moved `ovs-p4rt.h` from the `include/openvswitch` folder to  a new `include/ovsp4rt` folder. Updated the buildsystem to reflect the change.

- Updated #include paths from `"openswitch/ovs-p4rt.h"` to `"ovsp4rt/ovs-p4rt.h"`.

- Implemented an `install-data-hook` buildsystem target to create a symbolic link to `include/ovsp4rt/ovs-p4rt.h` in the `include/openvswitch` folder of the install tree, to maintain backward compatibility with `networking-recipe`. Modified the `dist-hook-git` target to ignore the symlink.

----

This PR is part of the process of moving `ovs-p4rt.h` from the `ovs` repository to the `networking-recipe` repository.

It causes ovs to mirror the ovs-p4rt include directory structure:

```text
include/
`-- ovsp4rt
    `-- ovs-p4rt.h
```

To provide backward compatibility during the transition, there are currently TWO copies of `ovs-p4rt.h`, which must be kept in sync.

A subsequent commit will change the `--with-p4ovs` parameter to accept an include directory path, falling back to the local copy if no path is provided.

The copy in the `ovs` repository will be removed after a suitable interval and before the P4OVS changes are upstreamed to the mothership.

### CODE REVIEW

**Comment by 5abeel** [comment]
> This PR is part of the process of moving ovs-p4rt.h from the ovs repository to the networking-recipe repository.

Why does the ovs-p4rt.h need to move to networking-recipe?

**Comment by ffoulkes** [comment]
> Why does the ovs-p4rt.h need to move to networking-recipe?

Because `ovs-p4rt.h` is part of `ovs-p4rt`, and ovs-p4rt is currently part of `networking-recipe`.

A component owns its own external interface. The header files (and other collateral, such as pkg-config files) are published by the component in order for other pieces of software to use the component. `ovs-p4rt.h` is the header file that defines ovsp4rt's external interface. It is updated because of changes made to ovs-p4rt, not changes made to ovs. It therefore belongs with ovs-p4rt in networking-recipe.

**Review by 5abeel — APPROVED** [review]
LGTM

**Comment by ffoulkes** [comment]
I don't know if this helps, but it illustrates the dependencies and the build order this implies:

P4CP - Build dependencies

**Pull request merged**
