### PR TITLE
Updated PTF test script README with more information

### PR DESCRIPTION
**Pull request by dkaranjai**
Signed-off-by: Dwaipayan Karanjai <dwaipayan.karanjai@intel.com>

### CODE REVIEW

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-67-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/3e9a731e4de48a66b7935ea890bcf09658662332

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-67-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/3e9a731e4de48a66b7935ea890bcf09658662332

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-67-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/3e9a731e4de48a66b7935ea890bcf09658662332

**Review by stadju — APPROVED** [review]

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-67-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/3e9a731e4de48a66b7935ea890bcf09658662332

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-67-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6deb02d7f8cfb0eff4bfab422236dac91fe196e9

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-67-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6deb02d7f8cfb0eff4bfab422236dac91fe196e9

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-67-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/230c561df6d4f8b3f5f3821cf41bd5665b5ff891

**Review by sijubaker — APPROVED** [review]

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-67-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/5e2b15bffc30e8ef5171d77ade0140c55a355730

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-67-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/5e2b15bffc30e8ef5171d77ade0140c55a355730

**Pull request merged**
