### PR TITLE
Adding scripts and json files dpdk action profile/selector CLI tests

### PR DESCRIPTION
**Pull request by dkaranjai**
Signed-off-by: Dwaipayan Karanjai <dwaipayan.karanjai@intel.com>

### CODE REVIEW

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/nex-epgsw-ipdkci/GitHub_MultiBranch_Pipelines/ovs/PR-37-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/4399711a76752a1e582982de3b41f185c5cfb253

**Comment by dkaranjai** [comment]
OVS build passed:

libtool: install: /usr/bin/install -c utilities/ovs-appctl /usr/local/bin/ovs-appctl
libtool: install: /usr/bin/install -c utilities/ovs-testcontroller /usr/local/bin/ovs-testcontroller
libtool: install: /usr/bin/install -c utilities/ovs-dpctl /usr/local/bin/ovs-dpctl
libtool: install: /usr/bin/install -c utilities/ovs-ofctl /usr/local/bin/ovs-ofctl
libtool: install: /usr/bin/install -c utilities/ovs-vsctl /usr/local/bin/ovs-vsctl
libtool: install: /usr/bin/install -c utilities/gnmi-cli /usr/local/bin/gnmi-cli
libtool: install: /usr/bin/install -c utilities/ovs_pipeline_builder /usr/local/bin/ovs_pipeline_builder
libtool: install: /usr/bin/install -c ovsdb/ovsdb-tool /usr/local/bin/ovsdb-tool
libtool: install: /usr/bin/install -c ovsdb/ovsdb-client /usr/local/bin/ovsdb-client
libtool: install: /usr/bin/install -c vtep/vtep-ctl /usr/local/bin/vtep-ctl
make[3]: Leaving directory '/root/dkaranjai/ipdk_ptf'
make[2]: Leaving directory '/root/dkaranjai/ipdk_ptf'
make[1]: Leaving directory '/root/dkaranjai/ipdk_ptf'

**Review by djayakum — APPROVED** [review]

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-37-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/4399711a76752a1e582982de3b41f185c5cfb253

**Review by vsureshkumarp — APPROVED** [review]
Looks good

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/PR-37-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/4399711a76752a1e582982de3b41f185c5cfb253

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-37-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/4399711a76752a1e582982de3b41f185c5cfb253

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-37-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/e131eed491dc266cab3cf9643d4a5897e6a4aec0

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-37-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/84cf6d0ebdc294b799b760c7b821c0c27f66da7f

**Comment by nupuruttarwar** [comment]
Looks good to me

**Review by nupuruttarwar — APPROVED** [review]

**Pull request merged**
