### PR TITLE
Lnt feature tc

### PR DESCRIPTION
**Pull request by dkaranjai**

### CODE REVIEW

**Comment by dkaranjai** [comment]
all passed logs are here http://10.233.134.180/ptf/ipdk_lnt/

**Review by monikajagia — APPROVED** [review]
Looks good. However, the branch seems out of date. Please check once.

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-48-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7885a5b06d545aca5903b97105ec54e2f6cc31dc

**Comment by sjwahub** [comment]
Below files are updated by copying them from p4proto/p4src/linux_networking in latest build 0.7.4.5.5. Is it legit ?

    common/p4c_artifacts/linux_networking/linux_networking.p4
    common/p4c_artifacts/linux_networking/lnw_ct.p4

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-48-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7885a5b06d545aca5903b97105ec54e2f6cc31dc

**Comment by 5abeel** [comment]
General comment: 
- Avoid using cryptic/abbreviated commit messages. 
- Some explanation of what the details are in descriptions would be helpful

**Comment by 5abeel** [comment]
> all passed logs are here http://10.233.134.180/ptf/ipdk_lnt/

Another general comment: Links internal to a company should not be posted on public open-source forums

**Review by 5abeel — CHANGES_REQUESTED** [review]
Please update commit message (not a good idea to use cryptic messages) and add description.

Message and description should give enough detail for someone outside your team on what this commit is fixing

**Comment by sjwahub** [comment]
Automated Linux networking test cases for following scenarios.
1. lnt_2hotplugvm_vxlan_2nsvm.py test case: 
   P4OVS along with two Hotplug VMs are deployed on localhost. Legacy OVS and two ip netns VMs are deployed on remote host. Vxlan is deployed between hosts

2. lnt_2vm_vxlan_2nsvm_5min_ping.py test case:
   Continuous 5 minutes ping from local VM to remote VM is executed for above test case 1.

 3. lnt_4vm_full_mesh.py.
    Full mesh ping among local VMs and remove VMs for above test case 1

4.  lnt_4vm_2host_add_dele_rule.py test case
     Add and delete traffic rule and verify traffic accordingly upon rule’s existence. 

5. lnt_ctrl_vhost_port_flap.py
    Flap vhost port, vlan port and  vxlan control port and verify traffic accordingly upon the port state of up or down.

6. lnt_1hotplugvm_vxlan_1nsvm.py
     P4OVS along with one Hotplug VMs are deployed on localhost. Legacy OVS and one ip netns VMs are deployed on remote host. Vxlan is deployed between hosts

7. lnt_4vm_on_same_host.py test case:
    Four standard VMs are created on same host.  VLANs connectivity are deployed among VMs. Change code execution sequence by moving set-pipe code after VM creation code.

Test logs 

- [ptf_tests_suite1.log.txt](https://github.com/ipdk-io/ovs/files/9348367/ptf_tests_suite1.log.txt)
- [ptf_tests_suite2.log.txt](https://github.com/ipdk-io/ovs/files/9348369/ptf_tests_suite2.log.txt)
- [max_pot.log.txt](https://github.com/ipdk-io/ovs/files/9348370/max_pot.log.txt). It failed in above ptf_tests_suite2.log.txt. The failure is test suite self issue. Thus unit test is used as proof.
- [ovs_build.log.txt](https://github.com/ipdk-io/ovs/files/9348371/ovs_build.log.txt)

**Comment by sjwahub** [comment]
> http://10.233.134.180/ptf/ipdk_lnt/

The logs are too large. It's not good to paste here. I couldn't find a way to attached large log file. Any suggestion?

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-48-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/13e0d4b66afdbffa54ad44bf69814439bf114759

**Review by 5abeel — APPROVED** [review]

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-48-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/13e0d4b66afdbffa54ad44bf69814439bf114759

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-48-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/13e0d4b66afdbffa54ad44bf69814439bf114759

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-48-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/13e0d4b66afdbffa54ad44bf69814439bf114759

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-48-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9d3591e8905f16b73f68a8b87d159d13c45187c4

**Comment by dkaranjai** [comment]
Can this be merged?

**Comment by nupuruttarwar** [comment]
yes, please update the commit message as well to reflect this - https://github.com/ipdk-io/ovs/pull/48#issuecomment-1214634474 and then it can be merged

**Pull request merged**
