### PR TITLE
Update limitations in the document

### PR DESCRIPTION
**Pull request by n-sandeep**
This review captures limitations across all features supported
by ovs-with-p4

Signed-off-by: n-sandeep <sandeep.nagapattinam@intel.com>

### CODE REVIEW

**Comment by n-sandeep** [comment]
This is still a draft review, need to re-work. 
Will make review public once other issues are addressed.

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-40-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9ffcdf30210ce2a93d415a40cefd697b116d1a54

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-40-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/cca4f12d885ce0fbd20afe8813aa8bcff20238cc

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-40-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/0c12a7e26a12adc42f9020738eda625fe403438e

**Review by vsureshkumarp — APPROVED** [review]
Looks good to me.

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-40-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/0c12a7e26a12adc42f9020738eda625fe403438e

**Pull request merged**
