### PR TITLE
Adding config_control_port_with_link

### PR DESCRIPTION
**Pull request by dkaranjai**
Signed-off-by: Dwaipayan Karanjai <dwaipayan.karanjai@intel.com>

### CODE REVIEW

**Comment by dkaranjai** [comment]
checked p4ovs build on this branch, all okay:

pipeline_builder ovsdb/ovsdb-tool ovsdb/ovsdb-client vtep/vtep-ctl '/usr/local/bin'
libtool: install: /usr/bin/install -c utilities/ovs-appctl /usr/local/bin/ovs-appctl
libtool: install: /usr/bin/install -c utilities/ovs-testcontroller /usr/local/bin/ovs-testcontroller
libtool: install: /usr/bin/install -c utilities/ovs-dpctl /usr/local/bin/ovs-dpctl
libtool: install: /usr/bin/install -c utilities/ovs-ofctl /usr/local/bin/ovs-ofctl
libtool: install: /usr/bin/install -c utilities/ovs-vsctl /usr/local/bin/ovs-vsctl
libtool: install: /usr/bin/install -c utilities/gnmi-cli /usr/local/bin/gnmi-cli
libtool: install: /usr/bin/install -c utilities/ovs_pipeline_builder /usr/local/bin/ovs_pipeline_builder
libtool: install: /usr/bin/install -c ovsdb/ovsdb-tool /usr/local/bin/ovsdb-tool
libtool: install: /usr/bin/install -c ovsdb/ovsdb-client /usr/local/bin/ovsdb-client
libtool: install: /usr/bin/install -c vtep/vtep-ctl /usr/local/bin/vtep-ctl
make[3]: Leaving directory '/root/dkaranjai/ipdk_dkaranjai_fork'
make[2]: Leaving directory '/root/dkaranjai/ipdk_dkaranjai_fork'
make[1]: Leaving directory '/root/dkaranjai/ipdk_dkaranjai_fork'

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-41-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/739695e406aa102393c4b228a01d0092896e8cb9

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-41-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/f694ea13c6c0c4ce654eb848d283dd092ecca3b9

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-41-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/8477d897f87d7d850e60e829ef657e4320c08380

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-41-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/924d4c6651a5c42e580e604e90dd33a954ec7540

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-41-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/ac44d62ff034a6e1fd3dca0edde5176817bfd0c4

**Comment by dkaranjai** [comment]
build verified after amend:

libtool: install: /usr/bin/install -c utilities/ovs-appctl /usr/local/bin/ovs-appctl
libtool: install: /usr/bin/install -c utilities/ovs-testcontroller /usr/local/bin/ovs-testcontroller
libtool: install: /usr/bin/install -c utilities/ovs-dpctl /usr/local/bin/ovs-dpctl
libtool: install: /usr/bin/install -c utilities/ovs-ofctl /usr/local/bin/ovs-ofctl
libtool: install: /usr/bin/install -c utilities/ovs-vsctl /usr/local/bin/ovs-vsctl
libtool: install: /usr/bin/install -c utilities/gnmi-cli /usr/local/bin/gnmi-cli
libtool: install: /usr/bin/install -c utilities/ovs_pipeline_builder /usr/local/bin/ovs_pipeline_builder
libtool: install: /usr/bin/install -c ovsdb/ovsdb-tool /usr/local/bin/ovsdb-tool
libtool: install: /usr/bin/install -c ovsdb/ovsdb-client /usr/local/bin/ovsdb-client
libtool: install: /usr/bin/install -c vtep/vtep-ctl /usr/local/bin/vtep-ctl
make[3]: Leaving directory '/root/dkaranjai/ipdk_dkaranjai_fork'
make[2]: Leaving directory '/root/dkaranjai/ipdk_dkaranjai_fork'
make[1]: Leaving directory '/root/dkaranjai/ipdk_dkaranjai_fork'

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-41-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6e94f4ce94377a77d31703c786a77aebed49eaca

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-41-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/f81b7569dd88ad2846b854b1ddc17ca3f0aa1a58

**Comment by sjwahub** [comment]
> checked p4ovs build on this branch, all okay:
> 
> pipeline_builder ovsdb/ovsdb-tool ovsdb/ovsdb-client vtep/vtep-ctl '/usr/local/bin' libtool: install: /usr/bin/install -c utilities/ovs-appctl /usr/local/bin/ovs-appctl libtool: install: /usr/bin/install -c utilities/ovs-testcontroller /usr/local/bin/ovs-testcontroller libtool: install: /usr/bin/install -c utilities/ovs-dpctl /usr/local/bin/ovs-dpctl libtool: install: /usr/bin/install -c utilities/ovs-ofctl /usr/local/bin/ovs-ofctl libtool: install: /usr/bin/install -c utilities/ovs-vsctl /usr/local/bin/ovs-vsctl libtool: install: /usr/bin/install -c utilities/gnmi-cli /usr/local/bin/gnmi-cli libtool: install: /usr/bin/install -c utilities/ovs_pipeline_builder /usr/local/bin/ovs_pipeline_builder libtool: install: /usr/bin/install -c ovsdb/ovsdb-tool /usr/local/bin/ovsdb-tool libtool: install: /usr/bin/install -c ovsdb/ovsdb-client /usr/local/bin/ovsdb-client libtool: install: /usr/bin/install -c vtep/vtep-ctl /usr/local/bin/vtep-ctl make[3]: Leaving directory '/root/dkaranjai/ipdk_dkaranjai_fork' make[2]: Leaving directory '/root/dkaranjai/ipdk_dkaranjai_fork' make[1]: Leaving directory '/root/dkaranjai/ipdk_dkaranjai_fork'

Here is the unit test log http://10.233.134.180/ptf/ctrl_port_with_link_fix/unittest.log

**Review by nupuruttarwar — APPROVED** [review]
Looks good to me

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-41-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/f81b7569dd88ad2846b854b1ddc17ca3f0aa1a58

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-41-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/f81b7569dd88ad2846b854b1ddc17ca3f0aa1a58

**Review by vsureshkumarp — APPROVED** [review]
Looks good to me.

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-41-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/ae5a3594fabe7a02b279507be53be4a7d983b608

**Pull request merged**
