### PR TITLE
Restores tests_to_run.txt in the event of a crash

### PR DESCRIPTION
**Pull request by dkaranjai**
Signed-off-by: Dwaipayan Karanjai <dwaipayan.karanjai@intel.com>

### CODE REVIEW

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/f360351bc4614514fe98e67c7177fa732b58199d

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/f360351bc4614514fe98e67c7177fa732b58199d

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/f360351bc4614514fe98e67c7177fa732b58199d

**Review by sijubaker — APPROVED** [review]

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7222c784ceedb1ebc66246d1e3333519eef5cdd7

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/0804af4684f7d779f2a8c77ef17ab034b4881e9e

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/0804af4684f7d779f2a8c77ef17ab034b4881e9e

**Review by stadju — APPROVED** [review]

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/ba727072e2e2b8735c56bd7c5622991ff76cdb32

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/ba727072e2e2b8735c56bd7c5622991ff76cdb32

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/ba727072e2e2b8735c56bd7c5622991ff76cdb32

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/e70fe416dcc956b49859166c6897c816700238b2

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-11/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9b7a484dec479de078d931d2757781fe9a0a29e0

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-12/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9b7a484dec479de078d931d2757781fe9a0a29e0

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-13/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9b7a484dec479de078d931d2757781fe9a0a29e0

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-14/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9b7a484dec479de078d931d2757781fe9a0a29e0

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-15/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9b7a484dec479de078d931d2757781fe9a0a29e0

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-72-16/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/57f0bd2b6c5c727e7faca3ccdf7ba5dd1bf47ed1

**Pull request merged**
