### PR TITLE
fix l3 action profile and selector deleting failure

### PR DESCRIPTION
**Pull request by sjwahub**
Signed-off-by: Shujun Wang <shujun.wang@intel.com>

1. Currently most of l3 action profile and selection script fail to delete member or group of a policy, for example
     FAIL; ovs-p4ctl del entry Failed with error: 'ingress.ipv4_host' has no attribute 'member_id'

2. This PR is to fix above failure. An example of correct message is provided 

    Deleting groups
    PASS: ovs-p4ctl del group group_id=1
    PASS: ovs-p4ctl del group group_id=2
    Deleting members
    PASS: ovs-p4ctl del member member_id=1
    PASS: ovs-p4ctl del member member_id=2

 A detailed log provided here for all l3 action profile and selector test cases:  [ptf_tests_runAll36.log](https://github.com/ipdk-io/ovs/files/9650364/ptf_tests_runAll36.log)

### CODE REVIEW

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-74-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/fd4973c7120d1aa75dbae18bf303e25af67b3dbf

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-74-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/fd4973c7120d1aa75dbae18bf303e25af67b3dbf

**Review by dkaranjai — APPROVED** [review]

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-74-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9e2dcbd468115e10579b3d3784b6435ac1137b58

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-74-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/fe5af22b1e5075c7eeec2c7a1f3c3c143aadd283

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-74-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/fe5af22b1e5075c7eeec2c7a1f3c3c143aadd283

**Comment by sjwahub** [comment]
Looks like PR74 is part of PR75.  Suggest to use PR75 instead and abandon this PR 74.

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-74-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/92902f848047c9b163836b86519a4daf41f182da

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-74-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/92902f848047c9b163836b86519a4daf41f182da

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-74-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/92902f848047c9b163836b86519a4daf41f182da

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-74-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/e684799f70bbd662e1c03b58278bc37c897b4dd4

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-74-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/e684799f70bbd662e1c03b58278bc37c897b4dd4

**Review by stadju — APPROVED** [review]

**Pull request merged**
