### PR TITLE
Fix pre_test.sh custom path variable issue

### PR DESCRIPTION
**Pull request by sjwahub**

### CODE REVIEW

**Comment by sjwahub** [comment]
Even by its own definition, the variable $3 should be $P4OVS_DEPS_INSTALL.   With this fix, below command proves it works.

source pre_test.sh  $SDE_INSTALL  $P4OVS_INSTALL_PATH $P4OVS_DEPS_INSTALL

```
> [root@wp26 ptf_tests]# source pre_test.sh  $SDE_INSTALL  $P4OVS_INSTALL_PATH $P4OVS_DEPS_INSTALL
> Killing qemu
> killing ovs
> sleeping for 2 seconds
> removing any vhost users from /tmp
> changing directory to /home/saldju/Release23/drop2/p4ovs
> sourcing p4ovs_env_setup.sh
> OS and Version details...
> Fedora : 33
> 
> ........... Omitted ................
> bf_switchd: dev_id 0 initialized
> 
> bf_switchd: initialized 1 devices
> Skip p4 lib init
> Skip mav diag lib init
> bf_switchd: spawning cli server thread
> bf_switchd: running in background; driver shell is disabled
> bf_switchd: server started - listening on port 9999
> I20221107 13:11:43.473182 102242 bf_sde_wrapper.cc:1671] switchd started successfully
> I20221107 13:11:43.473209 102242 bf_interface.cc:89] Detected is_sw_model: 1
> I20221107 13:11:43.473223 102242 bf_interface.cc:90] SDE version: 9.5.0
> 2022-11-07T21:11:43Z|00005|reconnect|INFO|unix:/home/saldju/Release23/drop2/p4ovs/deps/P4OVS_DEPS_INSTALL/var/run/openvswitch/db.sock: connecting...
> 2022-11-07T21:11:43Z|00006|reconnect|INFO|unix:/home/saldju/Release23/drop2/p4ovs/deps/P4OVS_DEPS_INSTALL/var/run/openvswitch/db.sock: connected
> 2022-11-07T21:11:43Z|00001|switch_vrf|INFO|vrf init successful on device 0
> 2022-11-07T21:11:43Z|00002|switch_rmac|INFO|rmac init successful on device 0
> 2022-11-07T21:11:43Z|00003|switch_rmac|INFO|rmac group created on device 0, rmac handle 0x12000001
> 2022-11-07T21:11:43Z|00004|switch_nhop|INFO|nhop group handle created on device 0 nhop group handle 0x90000001
> 2022-11-07T21:11:43Z|00005|switch_vrf|INFO|vrf created on device 0 vrf id 0 handle 0xa000001
> All Processes Started.....
> sleeping for 5 seconds
> setting the alias for PATH and LD_LIBRARY_PATH
> changing directory to ptf_tests
> /root/sjwang/ptf/lnt_ecmp_enhance/ptf_tests
> 
```

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-86-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/53c26916f1465bcd06ba69541228b100fd6864ac

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-86-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/d438bbd0c6fddab1432d1c50c0249db0c8b74a43

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-86-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/d438bbd0c6fddab1432d1c50c0249db0c8b74a43

**Review by dkaranjai — APPROVED** [review]
looks good

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-86-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/4734e8c3b2380b65d9ed66bde188f2063956a8d6

**Review by sijubaker — APPROVED** [review]

**Pull request merged**
