### PR TITLE
P4-OVS: Add exit code to build script

### PR DESCRIPTION
**Pull request by nupuruttarwar**
Title: Add exit code to build script
Signed-off-by: nupuruttarwar <nupur.uttarwar@intel.com>

### CODE REVIEW

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-53-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/a412f128475429eb247a1224cb008cb99052fecc

**Review by 5abeel — APPROVED** [review]
lgtm

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-53-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/a412f128475429eb247a1224cb008cb99052fecc

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-53-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/a412f128475429eb247a1224cb008cb99052fecc

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-53-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/a412f128475429eb247a1224cb008cb99052fecc

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-53-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/a412f128475429eb247a1224cb008cb99052fecc

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-53-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/a412f128475429eb247a1224cb008cb99052fecc

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-53-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/bea17847333ca83921d82230a1f9a784007eab7c

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-53-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/bea17847333ca83921d82230a1f9a784007eab7c

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-53-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/bea17847333ca83921d82230a1f9a784007eab7c

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-53-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/02571a64ca716055640c28315bc46783e475fe61

**Review by np2-git — APPROVED** [review]

**Pull request merged**
