### PR TITLE
Enhance LNT  json data file and corresponding script

### PR DESCRIPTION
**Pull request by sjwahub**
In previous json data files of this PR , the linux command is directly defined in those files. It's not good practice like below example,
{
    "id": "2",
    "name": "VM1",
    "veth_if": "veth_vm1",
    "cmds": [
        "ip addr add 99.0.0.4/24 dev veth_vm1",
        "ip link set dev veth_vm1 up"
    ]
}

It should define variables and their value only, like below example. And then these commands can be constructed in the script.

{
    "id": "2",
    "name": "VM1",
    "veth_if": "veth_vm1",
    "peer_name": "veth_host_vm1",
    "ip": "99.0.0.4/24”
}

The PR #60 (lnt_ecmp) test_uitilty.py has fixed this issue. This PR is just a follow up of PR #60 to fix json file along with corresponding script.

1. Test to run for all LNT case log
[ptf_tests_runAll21.log](https://github.com/ipdk-io/ovs/files/9562240/ptf_tests_runAll21.log)
2. Rebuild ovs  log 
[ovs-switchbuildlog.txt](https://github.com/ipdk-io/ovs/files/9562243/ovs-switchbuildlog.txt)

### CODE REVIEW

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/2bd75d69a36744c164b0e1084e844aa6006d5c96

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/2bd75d69a36744c164b0e1084e844aa6006d5c96

**Review by dkaranjai — APPROVED** [review]

**Review by sijubaker — APPROVED** [review]
approved

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/bdbc9f2c1c42f5a05efa7875a0759a9f75f03cb6

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/d6a778ff1a56aca60b1d5cb402dd7089b103c913

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/d6a778ff1a56aca60b1d5cb402dd7089b103c913

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/167910cd8d58dbe03f669c5ac472a887abc1271e

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/167910cd8d58dbe03f669c5ac472a887abc1271e

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/167910cd8d58dbe03f669c5ac472a887abc1271e

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/95dea31c84d47627c636500deb29037c8860dc52

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/37f0012b4cf2a3ee29269db3e3243b79682bac69

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-11/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/37f0012b4cf2a3ee29269db3e3243b79682bac69

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-12/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/d03f343aa82362dae8c216b59c038abae448911b

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-13/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/d03f343aa82362dae8c216b59c038abae448911b

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-66-14/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/3f40972cf77850f5e57eadfb2b19f76dfa47d20e

**Pull request merged**
