### PR TITLE
Fix DPDK_Hot_Plug.py failure

### PR DESCRIPTION
**Pull request by sjwahub**
Current code failed due to below Error. It's caused by messed up check-in https://github.com/ipdk-io/ovs/pull/51/files.  

```
Traceback (most recent call `last):`
  File "tests/DPDK_Hot_Plug.py", line 93, in runTest
    vm1=self.config_data['vm'][1]
IndexError: list index out of range

```

Fix it by copying its original code. Here is the unit test log

root@wp34:~/sjwang_ptf/profile_seclector_fix/ptf_tests# ptf --test-dir tests/ DPDK_Hot_Plug --pypath $PWD --test-params="config_json='DPDK_Hot_Plug.json';vm_location_list='/home/admin2/VM/ubuntu-20.04-server-cloudimg-amd64_1.img'" --platform=dummy
/usr/local/bin/ptf:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Using packet manipulation module: ptf.packet_scapy
/usr/local/lib/python3.9/site-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated
  cipher=algorithms.Blowfish,
/usr/local/lib/python3.9/site-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated
  cipher=algorithms.CAST5,
DPDK_Hot_Plug.Dpdk_Hot_Plug ... (qemu-system-x86_64 -enable-kvm -smp 4 -m 512M  -boot c -cpu host -enable-kvm -nographic  -L /root/pc-bios -name Vm1  -hda /home/admin2/VM/ubuntu-20.04-server-cloudimg-amd64_1.img  -object memory-backend-file,id=mem,size=512M,mem-path=/dev/hugepages,share=on  -mem-prealloc  -numa node,memdev=mem  -monitor telnet::6650,server,nowait  -serial telnet::6550,server &)
qemu-system-x86_64: -serial telnet::6550,server: info: QEMU waiting for connection on: disconnected:telnet:0.0.0.0:6550,server=on
VM creation successful : Vm1
Sleeping for 30 seconds for the vms to come up
Command: ip a | egrep "[0-9]*: " | cut -d ':' -f 2 executed
PASS: gnmi-cli set "device:virtual-device,name:net_vhost0,host:host1,device-type:VIRTIO_NET,queues:1,socket-path:/tmp/vhost-user-0,port-type:LINK"
PASS: gnmi-cli get verified for device:virtual-device,name:net_vhost0,host:host1,device-type:VIRTIO_NET,queues:1,socket-path:/tmp/vhost-user-0,port-type:LINK
qemu-system-x86_64: warning: short-form boolean option 'vhostforce' deprecated
Please use vhostforce=on instead
PASS: gnmi-cli set "device:virtual-device,name:net_vhost0,hotplug:add,qemu-socket-ip:127.0.0.1,qemu-socket-port:6650,qemu-vm-mac:00:e8:ca:11:aa:01,qemu-vm-netdev-id:netdev0,qemu-vm-chardev-id:char1,native-socket-path:/tmp/vhost-user-0,qemu-vm-device-id:dev0"
PASS: gnmi-cli get verified for device:virtual-device,name:net_vhost0,hotplug:add,qemu-socket-ip:127.0.0.1,qemu-socket-port:6650,qemu-vm-mac:00:e8:ca:11:aa:01,qemu-vm-netdev-id:netdev0,qemu-vm-chardev-id:char1,native-socket-path:/tmp/vhost-user-0,qemu-vm-device-id:dev0
Command: ip a | egrep "[0-9]*: " | cut -d ':' -f 2 executed
interfaces:  ['ens4']
Test has PASSED
ok

----------------------------------------------------------------------
Ran 1 test in 79.218s

OK

### CODE REVIEW

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/dff946e6bd94e1508d04434f19ab23bac243cac8

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/dff946e6bd94e1508d04434f19ab23bac243cac8

**Review by dkaranjai — CHANGES_REQUESTED** [review]
other files part of PR74 is also seen here.

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/dff946e6bd94e1508d04434f19ab23bac243cac8

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/8cc2f957f73fe773105f9e9b1a360bc098f0285b

**Comment by sjwahub** [comment]
> other files part of PR74 is also seen here.

In same repo as PR74, I created a branch for Dpdk_Hot_plug. After its submission,  I realized that PR75 includes PR74.  Now I compare all action profile/selector file in both PR. All files are same.  Thus I suggest to use PR75 and abandon PR74.

**Review by stadju — APPROVED** [review]

**Review by dkaranjai — APPROVED** [review]

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/d5b93921f9e9e367088180d4f214b75832fe751b

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/d5b93921f9e9e367088180d4f214b75832fe751b

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/d5b93921f9e9e367088180d4f214b75832fe751b

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/cf5288c2d20601d20531f244c1bfce4115b31acd

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9558deb2dc2c9b4d9f9270f862f7897e935d94f9

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9558deb2dc2c9b4d9f9270f862f7897e935d94f9

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-11/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/9558deb2dc2c9b4d9f9270f862f7897e935d94f9

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-12/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/47c1ca85860ca2260b4b6493a95d94ba00425ec4

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-13/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/60459bffde106c51bd8d67890992dfc49913d4d7

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-75-14/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/60459bffde106c51bd8d67890992dfc49913d4d7

**Pull request merged**
