### PR TITLE
Backport ES2K changes to ipdk-io

### PR DESCRIPTION
**Pull request by ffoulkes**

### CODE REVIEW

**Review by nupuruttarwar — COMMENTED** [review]
IPV6 support is tested only for ES2K target and not for DPDK yet. Should we conditionalize the support?

**Comment by n-sandeep** [comment]
Looks good to me, We are not claiming IPv6 functionlity on DPDK. So upto user to configure, but stack might not work as expected

**Review by n-sandeep — APPROVED** [review]
Looks good to me

**Review by 5abeel — APPROVED** [review]
LGTM

**Comment by ffoulkes** [comment]
> IPV6 support is tested only for ES2K target and not for DPDK yet. Should we conditionalize the support?

That would require adding adding support for our xxxx_TARGET macros to OvS. I'd rather filter out what we don't support in ovs-p4rt.

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Pull request merged**
