### PR TITLE
P4-OVS: add support for multiple cpu architectures

### PR DESCRIPTION
**Pull request by aravid-marvell**
Tested with aarch64 and x86_64

Signed-off-by: Asaf Ravid <aravid@marvell.com>

### CODE REVIEW

**Review by mestery — APPROVED** [review]
LGTM

**Comment by ipdksw** [comment]
https://cbjenkins-fm.devtools.intel.com/teams-nex-epgsw-ipdkci/job/nex-epgsw-ipdkci/job/GitHub_MultiBranch_Pipelines/job/ovs/job/PR-20/ Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/nex-epgsw-ipdkci/GitHub_MultiBranch_Pipelines/ovs/PR-20-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/8fc262f5f7b682bd6196d29a38b0a1404eb89d3c

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/nex-epgsw-ipdkci/GitHub_MultiBranch_Pipelines/ovs/PR-20-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/1e95e00a1fb3111847c5c6cdaad60b686ea8ca3b

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/53119442e60b5c54903e23ae856ea537d8b3b4a2

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/53119442e60b5c54903e23ae856ea537d8b3b4a2

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/f35ff6024c2e2764e2d9701c3b1ea1c501f8a8cc

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-11/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/29b54ca332bf126545337f9e08d7e4a34fab492b

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-12/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/d7aa659e9817056f8d404ee4e193974534b9e8d3

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-13/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/c07de4fea79191e87c73220eb2e27e8705ac0dc6

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-14/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-15/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-16/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-17/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-18/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-19/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-20/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-21/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-22/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-23/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-24/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-25/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-26/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-27/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-28/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-29/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-30/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-31/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-32/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-33/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-34/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-35/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-36/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by ipdksw** [comment]
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-20-37/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/7f1ecf9218e158aacb8df4ab1ea1de9c1bb6dc31

**Comment by mestery** [comment]
I find it funny that the Jenkins job just keeps trying to run against this for some unknown reason. Regardless, I'm closing this one.

**Pull request closed without merging**
