### PR TITLE
Changes to pna.conf files [Adding Mempool and numa node]

### PR DESCRIPTION
**Pull request by depasupu**

### CODE REVIEW

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-85-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/e85100a4e4e5fc04c462740d663be0092a217f0e

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-85-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/e85100a4e4e5fc04c462740d663be0092a217f0e

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-85-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/e85100a4e4e5fc04c462740d663be0092a217f0e

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-85-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/eb42d2cbbe5a9b2815afcd0ac96b35b243913de9

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-85-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/eb42d2cbbe5a9b2815afcd0ac96b35b243913de9

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-85-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/eb42d2cbbe5a9b2815afcd0ac96b35b243913de9

**Comment by depasupu** [comment]
Logs for l3_exact_match, l3_action_selector,l3_action_profile TC run
[logs_NewPSA_action_profile_conf.txt](https://github.com/ipdk-io/ovs/files/9964727/logs_NewPSA_action_profile_conf.txt)
[logs_NewPSA_action_selector_conf.txt](https://github.com/ipdk-io/ovs/files/9964728/logs_NewPSA_action_selector_conf.txt)
[logs_NewPSA_l3_exact_match_conf.txt](https://github.com/ipdk-io/ovs/files/9964730/logs_NewPSA_l3_exact_match_conf.txt)

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-85-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/905777b7421c2656f237aca1593cb1af28b3c19c

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-85-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/700b3fa4ec4e487254c03c458c9e3261c494f4d0

**Comment by depasupu** [comment]
l2_exact_match logs
[logs_NewPSA_l2_exact_match_conf.txt](https://github.com/ipdk-io/ovs/files/9965009/logs_NewPSA_l2_exact_match_conf.txt)

**Comment by depasupu** [comment]
[logs_NewPSA_l2_exact_match_conf.txt](https://github.com/ipdk-io/ovs/files/9965021/logs_NewPSA_l2_exact_match_conf.txt)

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-85-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/700b3fa4ec4e487254c03c458c9e3261c494f4d0

**Comment by depasupu** [comment]
Please find the run logs for the below psa artifacts [Total:7]
l2_exact_match, l3_exact_match
l3_action_profile, l3_action_selector
"l3em_indirect_counter_psa",
"l3_exact_match_add_del"
"simple_l2l3_wcm",

[logs_NewPSA_l2_exact_match_conf.txt](https://github.com/ipdk-io/ovs/files/9966300/logs_NewPSA_l2_exact_match_conf.txt)
[logs_NewPSA_l2_l3_wcm_conf.txt](https://github.com/ipdk-io/ovs/files/9966301/logs_NewPSA_l2_l3_wcm_conf.txt)
[logs_NewPSA_l3_exact_adddel_emindirect_conf.txt](https://github.com/ipdk-io/ovs/files/9966302/logs_NewPSA_l3_exact_adddel_emindirect_conf.txt)
[logs_NewPSA_l3_exact_match_conf.txt](https://github.com/ipdk-io/ovs/files/9966303/logs_NewPSA_l3_exact_match_conf.txt)
[logs_NewPSA_action_profile_conf.txt](https://github.com/ipdk-io/ovs/files/9966305/logs_NewPSA_action_profile_conf.txt)
[logs_NewPSA_action_selector_conf.txt](https://github.com/ipdk-io/ovs/files/9966306/logs_NewPSA_action_selector_conf.txt)

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-85-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/3fb57243dda5c4cad1e896d11d92767f6daa87ac

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-85-11/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/3fb57243dda5c4cad1e896d11d92767f6daa87ac

**Review by hirentha — APPROVED** [review]
LGTM

**Review by sjwahub — APPROVED** [review]

**Comment by dkaranjai** [comment]
Closed as #PR87 is a better solution

**Pull request closed without merging**
