### PR TITLE
Added all script fixes and changes - PR197,199,200

### PR DESCRIPTION
**Pull request by dkaranjai**
Signed-off-by: Dwaipayan Karanjai <dwaipayan.karanjai@intel.com>

### CODE REVIEW

**Comment by dkaranjai** [comment]
ovs build checked:

libtool: install: /usr/bin/install -c utilities/ovs-appctl /usr/local/bin/ovs-appctl
libtool: install: /usr/bin/install -c utilities/ovs-testcontroller /usr/local/bin/ovs-testcontroller
libtool: install: /usr/bin/install -c utilities/ovs-dpctl /usr/local/bin/ovs-dpctl
libtool: install: /usr/bin/install -c utilities/ovs-ofctl /usr/local/bin/ovs-ofctl
libtool: install: /usr/bin/install -c utilities/ovs-vsctl /usr/local/bin/ovs-vsctl
libtool: install: /usr/bin/install -c utilities/gnmi-cli /usr/local/bin/gnmi-cli
libtool: install: /usr/bin/install -c utilities/ovs_pipeline_builder /usr/local/bin/ovs_pipeline_builder
libtool: install: /usr/bin/install -c ovsdb/ovsdb-tool /usr/local/bin/ovsdb-tool
libtool: install: /usr/bin/install -c ovsdb/ovsdb-client /usr/local/bin/ovsdb-client
libtool: install: /usr/bin/install -c vtep/vtep-ctl /usr/local/bin/vtep-ctl
make[3]: Leaving directory '/root/dkaranjai/drop4.5.5/ovs'
make[2]: Leaving directory '/root/dkaranjai/drop4.5.5/ovs'
make[1]: Leaving directory '/root/dkaranjai/drop4.5.5/ovs'

**Review by djayakum — APPROVED** [review]

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-36-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/374a9778f7cab94aa7d15e20a8932b6098e7425b

**Review by vsureshkumarp — APPROVED** [review]
looks good.

**Comment by nupuruttarwar** [comment]
Looks good to me

**Comment by ipdksw** [comment]
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-36-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/aed9f0885687507a2ec72a1d693a3cb03a4af9fa

**Pull request merged**
