### PR TITLE
fix  tests_to_run.txt problem

### PR DESCRIPTION
**Pull request by sjwahub**
Signed-off-by: Shujun Wang <shujun.wang@intel.com>

Fix test suite issue of tests_to_run.txt

1.  ptf test suite run didn't restore tests_to_run.txt completely. The variables of last few lines were not restored back but running values were kept.  Clean up this mess.
2.  add missing test cases lnt_2hotplugvm_vxlan_2nsvm:config_json='lnt_2hotplugvm_vxlan_2nsvm.json';vm_location_list='VM1,VM2';pci_bdf='BDF1,BDF2';remote_port='PORT1';client_cred='CLIENT'

4. test log  [ptf_tests_run11.log](https://github.com/ipdk-io/ovs/files/9413100/ptf_tests_run11.log)

### CODE REVIEW

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-56-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/e359aa54e5392260acbca3b34af0ed313901c9cd

**Review by dkaranjai — APPROVED** [review]
reviewed log, the file changed and verified with the tests in tests/ directory. All good.

**Review by sijubaker — APPROVED** [review]

**Comment by ipdksw** [comment]
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-56-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/76a45d2e3d97eea58644ccee05fb0e6e79ad512a

**Comment by dkaranjai** [comment]
merging as all checks passed

**Pull request merged**
